name: CI for Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust to your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: run-tests
        run: |
          pytest  # Adjust this command based on your testing framework
        continue-on-error: true  # Allow failure for custom branch creation

      - name: Check test results and handle branches
        id: check-test
        run: |
          if [ $? -eq 0 ]; then
            echo "Tests passed. Preparing to merge dev into main."
            echo "::set-output name=tests_passed::true"
          else
            echo "Tests failed. Creating a new branch with today's date."
            echo "::set-output name=tests_passed::false"
            BRANCH_NAME="failed-tests-$(date +%Y%m%d)"
            git checkout -b $BRANCH_NAME
            git push origin $BRANCH_NAME
          fi
        shell: bash

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: needs.test.outputs.check-test.tests_passed == 'true'

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Merge dev into main
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout main
          git merge dev
          git push origin main
