name: Python CI/CD Pipeline

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: write  # Nécessaire pour faire des pushs et des reset

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      lint_status: ${{ steps.set-lint-status.outputs.status }}
      test_status: ${{ steps.set-test-status.outputs.status }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        id: lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: true  # Permet au workflow de continuer même en cas d'erreur de linting

      - name: Set lint status
        id: set-lint-status
        run: echo "::set-output name=status::${{ steps.lint.outcome == 'success' }}"

      - name: Test with pytest
        id: test
        run: pytest
        continue-on-error: true  # Permet au workflow de continuer même en cas d'échec des tests

      - name: Set test status
        id: set-test-status
        run: echo "::set-output name=status::${{ steps.test.outcome == 'success' }}"

  fast-forward-master:
    needs: build-and-test
    if: ${{ needs.build-and-test.outputs.lint_status == 'success' && needs.build-and-test.outputs.test_status == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fast-forward master
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout master
          git merge --ff-only dev
          git push origin master

  handle-failure:
    needs: build-and-test
    if: ${{ needs.build-and-test.outputs.lint_status != 'success' || needs.build-and-test.outputs.test_status != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove failed commit from dev and create failure branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          UNIQUE_ID=$(date +'%Y%m%d%H%M%S')
          git branch failures/$UNIQUE_ID dev
          git reset --hard HEAD~1
          git push origin failures/$UNIQUE_ID
          git push origin dev --force
